### ISSUE TITLE
Error when syncing source

### ISSUE THREAD

**Issue by dieselman8228** [Halium/docs#165]
When trying to sync to the repo I get this error....

Traceback (most recent call last):
  File "/home/aaron/halium/.repo/repo/main.py", line 56, in <module>
    from subcmds.version import Version
  File "/home/aaron/halium/.repo/repo/subcmds/__init__.py", line 38, in <module>
    ['%s' % name])
  File "/home/aaron/halium/.repo/repo/subcmds/upload.py", line 27, in <module>
    from hooks import RepoHook
  File "/home/aaron/halium/.repo/repo/hooks.py", line 472
    file=sys.stderr)
        ^
SyntaxError: invalid syntax

I am trying to build for a Samsung tab 4.7.0 (degaswifi) any help would be appreciated.

**Comment by doniks** [comment]
I'm not sure, but maybe something to do with python 2 vs 3 and the version of the `repo` command you use?!

**Comment by dieselman8228** [comment]
I tried both commands out of the official build documentation. Is there a recommended python version?

**Comment by JamiKettunen** [comment]
I'm not sure much can be done here still years later, best build legacy Halium versions on legacy Ubuntu versions like 16.04 (or unfortunately maybe even 14.04) due to potentially many other incompatabilities from changes to userspace.

Python 2 was officially removed from repo since Ubuntu 24.04 LTS for example so there you'd have to find your own way around that anyway
